spring.application.name=megashop-clientes

spring.datasource.url=jdbc:mysql://localhost:3306/megashop_clientes
spring.datasource.username=root
spring.datasource.password=Jv150207@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true